"""create pessoas table

Revision ID: 46f2e4b5241e
Revises: 
Create Date: 2026-08-27 15:18:07.249292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f2e4b5241e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('status_aprovacao', sa.Enum('AGUARDANDO', 'APROVADO', 'NAO_APROVADO', name='statusaprovacao'), nullable=False),
    sa.Column('status_cadastro', sa.Enum('ABERTO', 'FECHADO', name='statuscadastro'), nullable=False),
    sa.Column('data_entrevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_status_aprovacao'), 'pessoas', ['status_aprovacao'], unique=False)
    op.create_index(op.f('ix_pessoas_status_cadastro'), 'pessoas', ['status_cadastro'], unique=False)
    op.create_index(op.f('ix_pessoas_telefone'), 'pessoas', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pessoas_telefone'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_status_cadastro'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_status_aprovacao'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
