"""adiciona unicidade ao nome da pessoa

Revision ID: 5bb4db446d3e
Revises: 7181eed2050e
Create Date: 2026-08-30 22:02:40.494718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb4db446d3e'
down_revision = '7181eed2050e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nome_completo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
