"""cria tabela pessoas

Revision ID: 7181eed2050e
Revises: 80543aa1c61b
Create Date: 2026-08-30 12:46:55.927145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7181eed2050e'
down_revision = '80543aa1c61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('status_aprovacao', sa.Enum('AGUARDANDO', 'APROVADO', 'NAO_APROVADO', name='statusaprovacao'), nullable=False),
    sa.Column('status_cadastro', sa.Enum('ABERTO', 'FECHADO', name='statuscadastro'), nullable=False),
    sa.Column('data_entrevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_status_aprovacao'), ['status_aprovacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_status_cadastro'), ['status_cadastro'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_telefone'), ['telefone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_telefone'))
        batch_op.drop_index(batch_op.f('ix_pessoas_status_cadastro'))
        batch_op.drop_index(batch_op.f('ix_pessoas_status_aprovacao'))

    op.drop_table('pessoas')
    # ### end Alembic commands ###
