"""adiciona verificacao de email ao admin

Revision ID: 80543aa1c61b
Revises: 07010046ee47
Create Date: 2026-08-28 12:14:28.599837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80543aa1c61b'
down_revision = '07010046ee47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('token_verificacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_verificacao_expira_em', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_unique_constraint(None, ['token_verificacao'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('token_verificacao_expira_em')
        batch_op.drop_column('token_verificacao')
        batch_op.drop_column('email_verificado')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
